
export const iconExtensions = {
    'fa-file-archive': /\.(0|001|002|003|7z.001|7z.002|__b|a00|a01|a02|aar|aba|aea|afzplug|ain|alz|apa|apks|ara|arc|arc|arc|arc.lh|arch00|archiver|ari|arj|ark|asar|asdb|ashbak|asr|asvf|b1|b6z|ba|ba2|bars|bh|blob|boo|bpa|brsar|bsa|bza|bzip|bzip2|c00|c01|c02|c10|caa|car|carc|cb7|cba|cbr|cbz|cbz|cca|cfs|cgz|chksplit|chunk001|cia|cl2arc|cng|cpa|cpgz|cpio|cpt|cpt|cxarchive|cytoidlevel|czp|daa|daf|dar|dcf|dco|dd|dgc|dwa|dzip|e4a|ear|edz|egg|enex|enlx|erp|erp|f3z|far|fcarch|fomod|gar|gar|gca|gfar|ggpack|gnutar|greenfoot|grf|gsba|gta|gtar|gz|gza|ha|har|hbc|hbc2|hbe|hcl|he|he0|he1|he2|he4|hki|hki1|hki2|hki3|hpk|hpk|hyp|iaa|ice|idt|igma|iplb|iqmol|ish|ita|iwa|ize|j|j01|ja|jar|jhh|jpa|jps|kgb|kma|la|lbr|lgp|lha|lif|lnx|lqr|maff|mar|mba|mba|mbw|md|mdzip|meo|mht|mzp|nar|narc|nba|nbf|nca|ndx|nop|npa|nwv|oar|omod|omp|p01|p19|pa|pack.gz|pae|paq6|paq7|paq8|paq8f|paq8l|paq8p|par|par2|part00000|pax|pba|pdmod|pe4|pe4|pea|phar|pim|pit|pla|pnh|prs|pwv|qda|qualsoftcode|r0|r00|r01|r02|r03|r04|r1|r2|r21|r30|radq|rar|ras|ress|rge|rgss2a|rgss3a|rgssad|rk|rnc|roca|rp2|rp9|rpa|rpkg|rsdk|sabl|sar|sarc|sav|sbsar|sc2archive|sdc|sea|sen|sfs|sfx|sga|sh|shar|shk|shr|si|sidx|sinf|sit|sitx|snagitstamps|snagstyles|sow|sparc|split|spt|sqx|ssm|supp|swc|szs|tar|tar.xz|tardist|tbz|td0|tg|tiger|til|tlzma|tpz|trim.cia|trs|ts4script|ttarch|twz|twzip|txz|tz|tzarc|u8|uc2|uea|uha|unity3d|ustar|viv|vlt|vol|volarchive|w02|wa|waff|war|warc|wbb|wdz|webarchive|webarchivexml|wolf|wu8|xar|xcarchive|xdi|xfl|xip|xz|yrcbck|yrcbkm|zap|zim|zip|zsm|zsplit|ztd|zz)$/i,
    'fa-file-audio': /\.(2sflib|3ga|a2m|a52|aa|aa3|aac|aan|aax|aaxplugin|abcd|abk|ac3|acb|acg|acm|acp|acr|act|adt|adts|adv|adx|afc|aif|aifc|aiff|aix|alac|ang|aob|ape|apl|ash|asr|at3|atm|atrac|au|au|aud|audionote|avi|avr|awb|awb|awc|axa|axp|bap|bcstm|bfstm|bfwav|bonk|brsar|brstm|bwg|c01|caf|caff|cda|cdda|cdr|cfa|ckb|ckbx|cpt|d00|d01|dcm|dct|dff|dig|drg|ds2|dts|dtshd|dw|dwa|dwd|ear|edl|est_uax|evr|f32|f4a|f64|fda|fev|flac|g721|g723|g726|gpk|gsm|gsm|hca|hdp|hma|hmi|hps|iaa|isma|jo|jo-7z|koz|l|la|lqt|lso|lvp|m1a|m2a|m4a|m4b|m4p|ma1|mdc|mi4|minincsf|mka|mlp|mo3|mp1|mp2|mp3|mpa|mpc|mpga|mpu|mt9|mul|muz|mx3|mx4|mx5|mx5template|nfa|nkb|nra|nsa|nus3bank|nvf|ofr|oga|ogg|oggstr|omg|opus|paf|pca|pd|pna|ppc|ppcx|ptcop|qcp|r|ra|ram|raw|rax|record|rip|rl|rmf|rmj|rso|rx2|s16|sad|saf|sample|sb|sd|sdii|sdt|seg|seq|sfap0|sfk|sfx|sgp|shn|sid|smp|sns|song|sph|stap|strm|sw|swa|swav|syn|syw|tak|tm2|tm8|tmc|toc|tsp|tta|tun|txw|u|u8|uax|ub|ulaw|ulw|uw|v2m|vap|vb|vdj|voc|vox|vqf|vrf|vst|vst3|w64|wav|wax|wma|wus|wv|xa|xa|xma|ym|zab|zpa|zvr)$/i,
    'fa-file-code': /\.(abc|abp|ac3|ada|aia|alac|amr|asm|asm|b2a|b64|bas|bb|bhx|bin|bs2|btoa|bur|bws|c|cbl|cbp|cbs|cbxml|cc|ccc|ccp|ccs|chef|ci|cob|cod|coverage|cp|cpg|cpi|cpp|cs|csa|csn|ctx|cu|cv|cxx|d|dart|dba|dc4|dcproj|depend|developerprofile|divx|dsym|dts|dvtcolortheme|dvtplugin|eba|el|enc|erl|euc|evrc|ex|exw|f|f2k|f90|f95|fimpp|flac|fpp|ftn|fxml|gcode|gct|gmd|go|groovy|gvy|gwk|h264|haml|hbx|hex|hqx|hxx|ideplugin|iwb|j2c|java|jbc|jl|jlr|jpc|jse|juk|kit|kt|layout|lisp|lit|livecode|lol|lsp|m|m|macbin|magik|make|mcp|mjd|ml|mobileprovision|mode1v3|mode2v3|mq4|mq5|mrsn|n|nbc|neko|nim|nqc|nxc|ob2|obj|octest|oggu|ogmu|ogwu|opju|osc|otmu|otpu|otrkey|otwu|owl|p|p6|p8|pbj|pbxbtree|pbxproj|pbxuser|pc|pcc|pcm|pde|perspective|perspectivev3|php|pl|pl1|playground|pli|plm|pn|postal|prc|pro|pwn|pyo|pyx|qc|qualsoftcode|qx|r|r|r3d|rb|rbj|rev|rkt|rle|rpyb|rs|rsa|rte|ruleset|s|sb|sc|scala|scc|scm|shproj|snippet|src|ss|sv|svh|swift|t|tbd|tcc|utf8|utxt|uu|uud|uue|v|v|vala|vbe|vc|vgc|vic|vp|w|wdgtproj|wem|wme|workspace|x|xcappdata|xcarchive|xccolortheme|xcconfig|xccrashpoint|xcdatamodel|xcdatamodeld|xcode|xcodeplugin|xcodeproj|xcplugin|xcplugindata|xcscheme|xcsnapshots|xcworkspace|xej|xel|xesc|xpp|xquery|xvid|xx|xxe|yab|ync|yuv|z1|z2|z3|z4|z5|z6|z7|z8)$/i,
    'fa-file-excel': /\.(3dr|4dv|aam|ab3|abcd|abp|aby|acc|adcp|adt|adx|aft|aifb|ald|ali|anme|aw|bci|bcm|bdic|bgl|bgt|bin|bjo|blb|bld|blg|box|brw|btm|bvp|cap|capt|cdf|cdx|cdx|cel|celtx|ckt|clm|clp|cma|cna|contact|crtx|csa|csv|ctf|cub|cvd|cvn|dal|dam|das|dat|dbd|dcf|dcm|dcmd|ddc|ddcx|dfproj|dif|dii|dm2|dmsp|dockzip|drl|dsb|dsy|dsz|dvdproj|dvo|dwi|ebuild|edi|efx|egp|emb|emlxpart|enex|enl|epw|er1|esx|ev|exif|exp|exx|fcpevent|fcs|fdb|fdb|ffwp|fhc|fil|flo|flp|fmat|fmc|fob|fop|fox|fpsl|fro|fsc|ftw|fxp|gan|gbr|gc|gcw|gdt|ged|gedcom|ggb|gno|gpi|grade|grf|grk|grr|grv|gs|gtp|gwk|h12|h13|h17|hcc|hce|hcu|hda|hdf|hl|hml|hst|huh|hyv|i5z|iba|id2|idx|idx|igc|ii|iif|ima|imt|in|ink|inp|inx|ip|isf|itl|itm|itmsp|itx|ivt|ixb|jasper|jdb|jef|jnt|jph|jrprint|jrxml|kap|kdc|key|keychain|kid|kismac|kpf|kpp|kpr|kpx|kpz|kth|l6t|lbl|lcm|ldif|lgh|lgi|lib|livereg|liveupdate|lix|lix|lms|lmx|lp7|lsf|lsl|lvm|m|mai|mat|mbg|mbg|mbx|mcd|mcdx|mdc|mdf|mdj|mdl|mdl|mdm|mdsx|mdx|menc|met|mex|mfo|mjk|mls|mmap|mmc|mmf|mmp|mmp|mnc|mno|moho|mosaic|mox|mph|mpkt|mpp|mpx|mth|mtw|mw|mwf|mws|myi|nbp|ncorx|ndk|ndx|net|nitf|not|notebook|np|npl|npt|nrl|obj|odp|odx|oeaccount|ofc|oft|ofx|ond|one|oo3|opju|opx|opx|otln|otp|out|ova|ovf|paf|pcapng|pcb|pcr|pd4|pd5|pdas|pdb|pds|pdx|pdx|pfc|phb|phm|photoslibrary|pj2|pjm|pka|pkb|pkh|pks|pkt|plw|pmo|pod|poi|potm|potx|ppf|ppf|pps|ppsm|ppsx|ppt|pptm|pptx|prdx|prj|prj|pro6plx|prs|pst|ptb|ptf|ptn|ptz|pxf|pxl|q08|q09|qb2009|qb2011|qb2012|qb2013|qb2014|qb2017|qbw|qdf|qfx|qif|qmbl|qmtf|qpb|qrp|quicken2015|quicken2017|quickendata|qvw|ral|rbt|rcg|rdb|rfa|rfo|rgo|rnq|roadtrip|rod|rodz|rou|rox|rp|rpp|rpt|rsc|rte|rte|rvt|sar|sav|sc45|sca|scd|sdf|sdf|sdp|sds|sen|seo|sgml|shw|sle|slp|slx|snag|snapfireshow|sps|spub|spv|sq|sqd|sqr|sta|stm|stp|styk|stykz|sub|svf|swk|t05|t06|t07|t08|t09|t10|t11|t12|t13|t16|t18|ta9|tar|tax2009|tax2010|tax2011|tax2013|tax2015|tax2016|tax2017|tax2018|tax2019|tb|tbk|tbl|tcc|tcx|tdb|tdl|tdm|tdt|te3|tef|tet|tfa|tkfl|tmx|topc|tpb|tpf|tra|trd|trk|trs|trs|tst|tsv|tt10|tt12|tt13|tt18|ttk|twb|twh|txd|txf|u10|uccapilog|ulf|ulz|upoi|usr|uwl|vcd|vce|vcf|vcs|vdb|vdf|vdx|vi|vmt|vok|vrd|vsx|vtx|vxml|wab|wb2|wb3|wdf|wea|wgt|wgt|windowslivecontact|wjr|wnk|wpc|wtb|xdb|xdna|xem|xfd|xfdf|xft|xlc|xlf|xlt|xmcd|xml|xmlper|xpg|xpj|xpt|xrdml|xrp|xsl|xslt|zap|zdc|zmc|_xls|_xlsx|dex|dqy|oqy|pde|pder|pxl|sxls|udf|xar|xl|xla|xlam|xlb|xlc|xld|xlk|xll|xlm|xls|xlsb|xlshtml|xlsm|xlsmhtml|xlsx|xlt|xlthtml|xltm|xltx|xlv|xlw|xlw|xum)$/i,
    'fa-file-image': /\.(001|2bp|360|411|73i|8ca|8ci|8pbs|8xi|9.png|abm|accountpicture-ms|acorn|acr|adc|afphoto|afx|agif|agp|aic|ais|albm|apd|apm|apng|aps|apx|arr|art|artwork|arw|ase|aseprite|avatar|avb|awd|awd|blkrt|blz|bm2|bmc|bmf|bmp|bmq|bmx|bmz|bpg|brk|brn|brt|bss|bti|bw|c4|cal|cals|cam|can|cd5|cdc|cdg|ce|cid|cimg|cin|cit|clip|cmr|colz|cpbitmap|cpc|cpd|cpg|cps|cpt|cpx|csf|ct|cut|dc2|dcm|dcx|ddb|dds|ddt|dgt|dib|dic|dicom|djv|djvu|dm3|dmi|dpx|drz|dt2|dtw|dvl|ecw|epp|exr|fac|face|fal|fax|fbm|fil|fits|flif|fpg|fpos|fppx|fpx|frm|g3|gbr|gcdp|gfb|gfie|ggr|gif|gih|gim|gmbck|gmspr|gp4|gpd|gro|grob|gry|hdp|hdr|hdrp|heic|heif|hf|hpi|hr|hrf|i3d|ic1|ic2|ic3|ica|icb|icn|icon|icpr|ilbm|img|imj|info|ink|insp|int|iphotoproject|ipick|ipx|itc2|ithmb|ivr|ivue|iwi|j|j2c|j2k|jas|jb2|jbf|jbg|jbig|jbig2|jbmp|jbr|jfi|jfif|jia|jif|jiff|jng|jp2|jpc|jpd|jpe|jpeg|jpf|jpg|jpg-large|jpg2|jps|jpx|jtf|jwl|jxr|kdi|kdk|kfx|kic|kodak|kpg|kra|lb|lbm|lif|lip|ljp|lrpreview|lzp|mac|mat|max|mbm|mbm|mcs|mdp|mdp|met|mic|miff|mip|mipmaps|mix|mng|mnr|mpf|mpo|mrb|mrxs|msk|msp|mxi|myl|ncd|ncr|nct|neo|nlm|nol|nwm|oc3|oc4|oc5|oci|odi|omf|oplc|ora|ota|otb|oti|ozb|ozj|ozt|pac|pal|pano|pap|pat|pbm|pc1|pc2|pc3|pcd|pcx|pdd|pdn|pe4|pe4|pfi|pfr|pgf|pgm|pi1|pi2|pi2|pi3|pi4|pi5|pi6|pic|pic|pic|picnc|pict|pictclipping|piskel|pix|pix|pixadex|pixela|pjp|pjpeg|pjpg|pm|pm3|pmg|pnc|png|pni|pnm|pns|pnt|pntg|pop|pov|pov|pp4|pp5|ppf|ppm|prw|psb|psd|psdc|psdx|pse|psf|psp|pspbrush|pspimage|ptex|ptg|ptk|pts|ptx|ptx|pvr|pwp|px|pxd|pxicon|pxm|pxr|pyxel|pza|pzp|pzs|qif|qmg|qti|qtif|ras|rcl|rcu|rgb|rgb|rgba|rgf|ric|rif|riff|rix|rle|rli|rpf|rri|rs|rsb|rsr|rtl|rvg|s2mv|sai|sar|sbp|scg|sci|scn|scp|sct|scu|sdr|sep|sfc|sff|sfw|sgd|sgi|shg|sid|sid|sig|sig|sim|skitch|skm|skypeemoticonset|sld|smp|sob|spa|spc|spe|sph|spiff|spj|spp|spr|sprite|sprite2|spu|sr|ste|stex|sumo|sun|suniff|sup|sva|svm|t2b|t2k|taac|targa|tb0|tbn|tex|texture|tfc|tg4|tga|thm|thm|thumb|tif|tif|tiff|tjp|tm2|tn|tn1|tn2|tn3|tny|tpf|tpi|tps|trif|tsr|tub|u|ufo|uga|ugoira|upf|urt|usertile-ms|v|vda|vff|vic|vicar|viff|vna|vpe|vrimg|vrphoto|vss|vst|wb0|wb1|wb2|wbc|wbd|wbm|wbmp|wbp|wbz|wdp|webp|wi|wic|wmp|wpb|wpe|wvl|xbm|xcf|xpm|xwd|y|ysp|yuv|zif|zif|zvi)$/i,
    'fa-file-pdf': /\.(drmx|drmz|enc|fpe|hpd|hpt|lpdf|pdc|pdf|pdf-1|pdfig|pdfs|pdfxml|pfl|spdf|zpi)$/i,
    'fa-file-powerpoint': /\.(pot|potm|potx|ppa|ppam|pps|ppsm|ppsx|ppt|ppthtml|pptm|pptmhtml|pptx|ppv)$/i,
    'fa-file-video': /\.(264|264|60d|787|ajp|amc|amv|aud|av|av3|avchd|avd|ave|avi|avm|awlive|axv|bik|bik|bik2|bin|bix|bk2|blz|bnp|box|bs4|bsf|bu|bvr|camv|ced|cine|clk|cpi|cpvc|crec|cvc|cx3|d3v|dad|dash|dat|dav|db2|dce|dcr|dcr|ddat|dem|dinfo|dlx|dmsk|dmsm|dmsm3d|dmss|dsy|dv|dv-avi|dv4|dvr-ms|dvx|evo|evo|exo|exp|eye|f4f|f4v|flv|fvt|g64|g64x|gcs|gifv|gpe|gts|gvi|gvp|h264|hdv|hevc|hlx|ifo|insv|irf|ismv|iva|ivf|ivr|ivs|jdr|jts|jvsg|jvsgz|k3g|kmv|lrv|lva|lvf|lvix|lvl|m15|m1pg|m1v|m2t|m2ts|m2v|m4e|m4v|m75|mgv|mj2|mjp|mjpeg|mjpg|mk3d|mkv|mmv|mob|mod|modd|moff|moi|mp2v|mp4|mp4.infovid|mp4v|mpeg1|mpeg2|mpg|mpg2|mpg4|mpv|mpv2|mts|mtv|mvp|mvy|mxv|mys|n3r|nfv|nrd|nsv|nut|nuv|ogv|orv|otrkey|pak|pgi|pkz|pmv|pns|pss|psv|pva|pvm|pvr|pz|qsv|r3d|ravi|rdb|rmv|roq|rum|rv|rvid|rvx|scribe|sec|sec|ser|sfvidcap|siv|smv|sns|str|sve|svi|tdx|thm|thp|tivo|tix|tod|tp0|tpd|trp|ts|tsv|tvs|usm|v264|vbc|vc1|vcpf|vcr|vcv|vdf|vdx|veg|vem|vep|vft|vfw|vfz|vgm|vgz|vgz|vid|video|viv|viv|vivo|vix|vmlf|vmlt|vob|vol|vp3|vp6|vp7|vpj|vro|vs4|vse|vsh|vsp|vtt|webm|wgi|wlvs|wmv|wvm|wvp|wvx|xml|xmv|xvid|y4m|yog|yuv)$/i,
    'fa-file-word': /\.(_doc|_docx|abi|abw|abx|aea|arp|arr|asd|awbr|awkw|awt|bak~|bna|boc|bpw|bzabw|chs|cht|clkw|cod|compressed|crashed|ctx|ctz|cww|doc|doc|dochtml|docm|docmhtml|docx|docxml|dot|dothtml|dotm|dotx|ecw|env|eqn|esf|ewl|gly|hwdt|hwp|ix2|jpn|kdbx|kor|kvtml|kwd|lab|lgc|lp2|lwp|mell|mellel|msim|mwf|mwp|ndoc|nt|ntx|ont|ontx|ot|otx|passwordwallet4|pdh|pdm|pdr|pdw|pdwr|pdz|pfx|pgpf|psw|psw|psw|psw6|pswx|puz|pwa|pwd|pwdp|pwdpl|pwi|pwl|pwrep|pwt|pwv|rwg|rzk|sdoc|sef|so-abi|spanisher|sw|tha|tpm|twm|twz|twzip|uw|uwl|vwl|wbk|wbk|wcm|wie|wll|wordlist|wp|wp4|wp5|wp6|wp7|wpa|wpc|wpd|wpd|wpd|wpe|wpf|wpg|wpk|wpm|wpp|wps|wpt|wpw|ws|wsd|zabw|{pb)$/i,
};

export const extensionToIcon = ( filepath ) => {
    const icons = Object.getOwnPropertyNames( iconExtensions );

    const iconMatch = Object.entries( iconExtensions ).findIndex( ( [ , regex ] ) => filepath.match( regex ) );

    if ( iconMatch !== -1 ) {
        return icons[ iconMatch ];
    }

    return 'fa-file';
};

export const filterUnmatchedIcons = ( paths ) =>
    Object.entries( iconExtensions )
        .filter( ( [ , regex ] ) => -1 !== paths.findIndex( ( path ) => path.match( regex ) ) )
        .map( ( [ icon, ] ) => icon );